
export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const GET_PULL_REQUESTS_START = 'GET_PULL_REQUESTS_START';
export const GET_PULL_REQUESTS_SUCCESS = 'GET_PULL_REQUESTS_SUCCESS';
export const GET_PULL_REQUESTS_ERROR = 'GET_PULL_REQUESTS_ERROR';

export const GET_REPOS_START = 'GET_REPOS_START';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_REPOS_ERROR = 'GET_REPOS_ERROR';

export const GET_ISSUES_START = 'GET_ISSUES_START';
export const GET_ASSIGNED_ISSUES_SUCCESS = 'GET_ASSIGNED_ISSUES_SUCCESS';
export const GET_CREATED_ISSUES_SUCCESS = 'GET_CREATED_ISSUES_SUCCESS';
export const GET_MENTIONED_ISSUES_SUCCESS = 'GET_MENTIONED_ISSUES_SUCCESS';
export const GET_SUBSCRIBED_ISSUES_SUCCESS = 'GET_SUBSCRIBED_ISSUES_SUCCESS';
export const GET_ALL_ISSUES_SUCCESS = 'GET_ALL_ISSUES_SUCCESS';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';


export const SET_TOKEN = 'SET_TOKEN';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_USER = 'SET_USER';
export const ADD_OWNER = 'ADD_OWNER';
export const REMOVE_OWNER = 'REMOVE_OWNER';
export const ADD_REPO = 'ADD_REPO';
export const REMOVE_REPO = 'REMOVE_REPO';
export const SET_ACTIVE_REPO = 'SET_ACTIVE_REPO';
export const SET_DARK_THEME = 'SET_DARK_THEME';
export const SET_IS_USER_VALID = 'SET_IS_USER_VALID';
export const SET_IS_REPO_VALID = 'SET_IS_REPO_VALID';
export const SET_IS_TOKEN_VALID = 'SET_IS_TOKEN_VALID';

export const NAVIGATE_TO = 'NAVIGATE_TO';
